// Generates the Hayase repository + extension code on the fly, so the access key and the
// user's choices (sub/dub, language, quality) live only in the import link, never in GitHub.
export function parsePrefs(q) {
  const audio = ['sub', 'dub', 'any'].includes(q.audio) ? q.audio : 'sub';
  const lang = /^[a-z]{2,3}(-[A-Za-z]{2,4})?$|^all$/i.test(String(q.lang || '')) ? String(q.lang).toLowerCase() : 'en';
  const quality = q.quality === 'best' ? 'best' : (/^\d{3,4}$/.test(String(q.quality || '')) ? String(q.quality) : '1080');
  const k = String(Math.min(Math.max(Number(q.k) || 3, 1), 6));
  return { audio, lang, quality, k };
}

const qs = (o) => new URLSearchParams(o).toString();

export function buildIndex(api, key, prefs) {
  const params = { ...(key ? { key } : {}), ...prefs };
  const label = `${prefs.audio.toUpperCase()} · ${prefs.lang} · ${prefs.quality === 'best' ? 'best' : prefs.quality + 'p'}`;
  return [{
    id: `aws-hayase-${prefs.audio}-${prefs.lang}`,
    name: `AWS Hayase (${label})`,
    version: '0.5.0',
    type: 'torrent',
    accuracy: 'high',
    ratio: 0,
    media: 'sub',
    languages: ['all'],
    nsfw: false,
    icon: 'https://github.com/Nanicommet.png',
    update: `${api}/hayase/index.json?${qs(params)}`,
    code: `${api}/hayase/ext.js?${qs(params)}`
  }];
}

export function buildExtensionCode(api, key, prefs) {
  return `// Generated by aws-hayase. Do not publish: contains your access key.
const API = ${JSON.stringify(api)};
const KEY = ${JSON.stringify(key || '')};
const PREFS = ${JSON.stringify(prefs)};
const headers = KEY ? { 'x-hayase-key': KEY } : {};

async function find(q) {
  const p = new URLSearchParams();
  (q.titles || []).slice(0, 3).forEach((t) => p.append('title', t));
  if (q.episode != null && q.episode !== '') p.set('episode', q.episode);
  if (q.resolution) p.set('resolution', q.resolution);
  for (const [k, v] of Object.entries(PREFS)) p.set(k, v);
  const r = await fetch(API + '/hayase/torrents?' + p, { headers });
  if (!r.ok) throw new Error('AWS Hayase backend: HTTP ' + r.status);
  const d = await r.json();
  if (d.preparing) throw new Error(d.message || 'Preparing on the server, try again in a minute.');
  return (d.results || []).map((x) => ({ ...x, date: new Date(x.date) }));
}

export default {
  async test() {
    const r = await fetch(API + '/health');
    if (!r.ok) throw new Error('AWS Hayase backend is unreachable');
    return true;
  },
  single: find,
  batch: async () => [],
  async movie(q) { return find({ ...q, episode: undefined }); }
};
`;
}
